services:
  - type: web
    name: offline-media-vault-backend
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
